### PR TITLE
Fixed the css aligning;

### LINKED ISSUE #71: Last breadcrumb is not alligned properly
**Description:** The last breadcrumb is allined as others

**Steps to reproduce:**
1. Go to Offers page
2. Take a look at the “Breadcrumbs”.

**Actual result**
Image

Image

The last bradcrumb not alligned as others.

**Expected result**
All breadcrumbs should be alligned equally

### PR DESCRIPTION
**Pull request by holus-bolus**
Changed the last breadcrumb centering.

Created additional css rules for the list to align all items of the list properly
image

302281659-9cb620b7-222a-4d97-a41b-c30948e64df1

### CODE REVIEW

**Review by Wiret02 — APPROVED** [review]

**Review by iaremchuk — APPROVED** [review]
An additional style applied conditionally: when isLast is true, it applies the styles.link styles along with the alignItems: 'center' property; otherwise, it applies only the styles.previous styles.
I can see that line 26 is commented and I believe it should be removed.

**Comment by holus-bolus** [comment]
> An additional style applied conditionally: when isLast is true, it applies the styles.link styles along with the alignItems: 'center' property; otherwise, it applies only the styles.previous styles. I can see that line 26 is commented and I believe it should be removed.

The promlem is not in the conditinal render, but in the MUI styles applying. I commented the previous solution to check whether we would be able to align these items with another solution.

**Review by VictoriaRodik — APPROVED** [review]

**Review by OliaHrytsak — APPROVED** [review]

**Comment by vlad-khrychov** [comment]
> > An additional style applied conditionally: when isLast is true, it applies the styles.link styles along with the alignItems: 'center' property; otherwise, it applies only the styles.previous styles. I can see that line 26 is commented and I believe it should be removed.
> 
> The promlem is not in the conditinal render, but in the MUI styles applying. I commented the previous solution to check whether we would be able to align these items with another solution.

So, if now styles works correct we can remove commented line?

**Comment by holus-bolus** [comment]
> > > An additional style applied conditionally: when isLast is true, it applies the styles.link styles along with the alignItems: 'center' property; otherwise, it applies only the styles.previous styles. I can see that line 26 is commented and I believe it should be removed.
> > 
> > 
> > The promlem is not in the conditinal render, but in the MUI styles applying. I commented the previous solution to check whether we would be able to align these items with another solution.
> 
> So, if now styles works correct we can remove commented line?

Yes, I removed it

**Review by online-marathon — APPROVED** [review]

**Pull request merged**
